import type { Metadata } from "next";
import "./globals.css";
import "./calendar.css"
import { ThemeProvider } from '../utils/theme'
import AuthProvider from "@/providers/AuthProvider";
import Navbar from "@/components/navbar/navbar";
import { ConditionalNavbar, ConditionalFooter } from "./conditionalRender";
import Footer from "@/components/footer/footer";
import CreditBar from "@/components/creditBar/creditBar";
import { GA } from "@/components/GA/GA";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ThemeProvider>
            <div className="container">
                <ConditionalNavbar />
                <div className="wrapper">
                  {children}   
                   <ConditionalFooter/>
                </div>
            </div>
            <CreditBar/>
            <GA/>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
