import type { Metadata } from "next";
import "./globals.css";
import "./calendar.css"
import { ThemeProvider } from '../utils/theme'
import AuthProvider from "@/providers/AuthProvider";
import Navbar from "@/components/navbar/navbar";
import ConditionalNavbar from "./conditionalRender";
import Footer from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ThemeProvider>
            <div className="container">
                <ConditionalNavbar />
                <div className="wrapper">
                  {children}
                </div>
                <Footer/>
            </div>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
